os:
- linux
language: rust
rust:
  - stable

global:
  - CRATE_NAME=rusty-pomodoro

matrix:
  include:
    - env:
      - NAME=rusty-pomodoro 
      - TARGET=x86_64-pc-windows-msvc
      - PACKAGE=${NAME}-${TARGET}.tar.gz
      os: linux

before_install:
  - set -e
  - rustup self update
  - rustup target add $TARGET
  - cargo test

cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
