os:
- linux
language: rust
rust:
  - stable

global:
  - CRATE_NAME=rusty-pomodoro

matrix:
  include:
    # OSX
    - env: 
      - NAME=rusty-pomodoro
      - TARGET=x86_64-apple-darwin
      - PACKAGE=${NAME}-${TARGET}.tar.gz
      os: osx
    # Windows
    - env:
      - NAME=rusty-pomodoro 
      - TARGET=x86_64-pc-windows-gnu
      - PACKAGE=${NAME}-${TARGET}.tar.gz
      os: ubuntu

before_install:
  - set -e
  - rustup self update

before_deploy:
  ci/before_deploy.sh

deploy:
  provider: releases
  file: $PACKAGE
  skip_cleanup: true
  api_key:
    secure: $GHKEY
  on:
    tags: true
    repo: ozangulle/rusty-pomodoro