os:
- linux
language: rust
rust:
  - stable

global:
  - CRATE_NAME=rusty-pomodoro

matrix:
  include:
    # OSX
    - env: 
      - NAME=rusty-pomodoro
      - TARGET=x86_64-apple-darwin
      - PACKAGE=$NAME-x86_64-apple-darwin.tar.gz
      os: osx
    # Windows
    - env:
      - NAME=rusty-pomodoro 
      - TARGET=x86_64-pc-windows-msvc
      - PACKAGE=$NAME-x86_64-pc-windows-msvc.tar.gz

before_install:
  - set -e
  - rustup self update

script:
 - cargo build --target $TARGET --verbose --release

before_deploy:
  - tar -czf $PACKAGE -C target/$TARGET/release/ $NAME

deploy:
  provider: releases
  file: ${PACKAGE}
  skip_cleanup: true
  on:
    tags: true
  repo: ozangulle/rusty-pomodoro